allowBuilds:
  esbuild: true
  "@parcel/watcher": false
  lmdb: false
  msgpackr-extract: false
blockExoticSubdeps: true
minimumReleaseAge: 10080
trustPolicy: no-downgrade
trustPolicyExclude:
  - "chokidar@4.0.3"
  - "ua-parser-js@0.7.41"
  - "semver@5.7.2 || 6.3.1"
packages:
  - "example"