require_relative '../../../node_modules/.pnpm/@capacitor+ios@5.5.1_@capacitor+core@5.7.8/node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '13.0'
use_frameworks! :linkage => :static

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../../node_modules/.pnpm/@capacitor+ios@5.5.1_@capacitor+core@5.7.8/node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../../node_modules/.pnpm/@capacitor+ios@5.5.1_@capacitor+core@5.7.8/node_modules/@capacitor/ios'
  pod 'CapacitorApp', :path => '../../../node_modules/.pnpm/@capacitor+app@5.0.6_@capacitor+core@5.7.8/node_modules/@capacitor/app'
  pod 'CapacitorCamera', :path => '../../../node_modules/.pnpm/@capacitor+camera@5.0.10_@capacitor+core@5.7.8/node_modules/@capacitor/camera'
  pod 'CapacitorFilesystem', :path => '../../../node_modules/.pnpm/@capacitor+filesystem@5.2.2_@capacitor+core@5.7.8/node_modules/@capacitor/filesystem'
  pod 'CapacitorGeolocation', :path => '../../../node_modules/.pnpm/@capacitor+geolocation@5.0.8_@capacitor+core@5.7.8/node_modules/@capacitor/geolocation'
  pod 'CapacitorHaptics', :path => '../../../node_modules/.pnpm/@capacitor+haptics@5.0.6_@capacitor+core@5.7.8/node_modules/@capacitor/haptics'
  pod 'CapacitorKeyboard', :path => '../../../node_modules/.pnpm/@capacitor+keyboard@5.0.6_@capacitor+core@5.7.8/node_modules/@capacitor/keyboard'
  pod 'CapacitorPreferences', :path => '../../../node_modules/.pnpm/@capacitor+preferences@5.0.8_@capacitor+core@5.7.8/node_modules/@capacitor/preferences'
  pod 'CapacitorStatusBar', :path => '../../../node_modules/.pnpm/@capacitor+status-bar@5.0.6_@capacitor+core@5.7.8/node_modules/@capacitor/status-bar'
  pod 'CordovaPlugins', :path => '../capacitor-cordova-ios-plugins'
end

target 'App' do
  capacitor_pods
  # Add your Pods here
end

post_install do |installer|
  assertDeploymentTarget(installer)
end
